<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Rig.Wpf.LegacyHost.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rig.Wpf.LegacyHost\Rig.Wpf.LegacyHost.csproj" />
    <ProjectReference Include="..\Rig.Wpf.TestHelpers\Rig.Wpf.TestHelpers.csproj" />
  </ItemGroup>

</Project>
