<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Rig.Wpf.RigMetier.Legacy.Tests</RootNamespace>
    <NoWarn>$(NoWarn);MSB3277;CS8002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rig.Wpf.RigMetier.Legacy\Rig.Wpf.RigMetier.Legacy.csproj" />
  </ItemGroup>

</Project>
