<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Rig.Wpf.Processus.Ipe.Tests</RootNamespace>
    <AssemblyName>Rig.Wpf.Processus.IPE.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rig.Wpf.Processus.IPE\Rig.Wpf.Processus.IPE.csproj" />
    <ProjectReference Include="..\Rig.Wpf.RigMetier\Rig.Wpf.RigMetier.csproj" />
  </ItemGroup>

</Project>
